version: '3'
x-airflow-common: &airflow-common
  image: apache/airflow:2.9.2
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./requirements.txt:/requirements.txt
  user: "${AIRFLOW_UID:-50000}:0"

services:
  airflow:
    <<: *airflow-common
    command: >
      bash -c "pip install -r /requirements.txt &&
               airflow db init &&
               airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com &&
               airflow webserver & airflow scheduler"
    ports:
      - "8080:8080"
